// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeDAKcwBUmFh9Rq9eAioE7S4Lj39WwyQg',
    appId: '1:620233064606:web:af8197e3f2ef7623a6fb8f',
    messagingSenderId: '620233064606',
    projectId: 'e-project-b3b74',
    authDomain: 'e-project-b3b74.firebaseapp.com',
    storageBucket: 'e-project-b3b74.firebasestorage.app',
    measurementId: 'G-QWLV0WZ656',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHYFEkDKb63LaA8BnfPDYIMBDseyw3eMA',
    appId: '1:620233064606:android:69d04a087eb348aca6fb8f',
    messagingSenderId: '620233064606',
    projectId: 'e-project-b3b74',
    storageBucket: 'e-project-b3b74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWE-rSU8Cwl1fe8PPQvuMjiF9iC634TE',
    appId: '1:620233064606:ios:067c630fa8cc1963a6fb8f',
    messagingSenderId: '620233064606',
    projectId: 'e-project-b3b74',
    storageBucket: 'e-project-b3b74.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBWE-rSU8Cwl1fe8PPQvuMjiF9iC634TE',
    appId: '1:620233064606:ios:067c630fa8cc1963a6fb8f',
    messagingSenderId: '620233064606',
    projectId: 'e-project-b3b74',
    storageBucket: 'e-project-b3b74.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeDAKcwBUmFh9Rq9eAioE7S4Lj39WwyQg',
    appId: '1:620233064606:web:656141f87781cecea6fb8f',
    messagingSenderId: '620233064606',
    projectId: 'e-project-b3b74',
    authDomain: 'e-project-b3b74.firebaseapp.com',
    storageBucket: 'e-project-b3b74.firebasestorage.app',
    measurementId: 'G-1YPET60P6M',
  );
}
